version: '3.4'

services:
  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserApi\Dockerfile

  emailworker:
    image: ${DOCKER_REGISTRY-}emailworker
    build:
      context: .
      dockerfile: EmailWorker\Dockerfile

